openjdk-6-jdk
openjdk-6-jre
openjdk-6-jre-headless
openjdk-6-jre-lib
openjdk-7-jdk
openjdk-7-jre
openjdk-7-jre-headless
openjdk-7-jre-lib
icedtea-6-jre-cacao
icedtea-6-jre-jamvm
icedtea-7-jre-jamvm
icedtea-netx
icedtea-6-jre-cacao
icedtea-6-jre-jamvm
icedtea-7-jre-jamvm
ca-certificates-java
java-common
libaccess-bridge-java
libaccess-bridge-java-jni
tzdata-java
